apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app:  mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app:  mysql
    spec:
      containers:
        - image:  mysql
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value:  root123
            - name: MYSQL_DATABASE
              value:  infinite
          ports:
            - containerPort:  3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
         - name: mysql-persistent-storage
           persistentVolumeClaim:
             claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    tier: database
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
    tier: database
  clusterIP: None  
    


         


